---
- name: Deploy Web App
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Install Nginx using DNF
      dnf:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        src: finexo-html
        dest: /usr/share/nginx/html/
        mode: '0644'
